/*
 * @file: App.h
 * @brief: 应用层主头文件。
 * @author: [Auto-generated by Roo]
 * @date: 2025/04/11
 * @description: 包含项目级的配置宏定义和所有应用层模块的头文件。
 */
#ifndef  _APP_H
#define  _APP_H

// --- 项目级硬件配置宏 ---
#define	GataFlag				0		// 继电器类型标志: 0 = 内置继电器, 1 = 外置继电器
#define	GataType				0		// 继电器型号或时序配置: 0 = 拉合闸时间200ms, 1 = 拉合闸时间35ms

// --- 显示配置宏 ---
#define DL645_MAX_CYCDISP       99    // 最大自动轮显项目数量
#define DL645_MAX_KEYDISP       99    // 最大按键显示项目数量

// --- 标准库头文件包含 ---
#include <math.h>   // 数学函数库 (例如用于校准计算中的浮点运算)
#include <stdio.h>  // 标准输入输出库 (可能用于调试打印等)
#include <string.h> // 字符串处理库 (例如用于地址比较 memcmp)
#include <stdlib.h> // 标准库 (例如用于内存分配 malloc, free)

// --- 驱动层头文件包含 ---
#include <Drive_Lib.h> // 驱动库主头文件 (包含所有底层驱动接口)
#include <Memory.h>    // 存储器(EEPROM/FRAM)读写接口头文件

// --- 应用层模块头文件包含 ---
#include <Scom.h>          // 串行通信模块头文件
#include <Dl645_Types.h>   // DL/T645协议相关的数据类型定义
#include <Dl645_File.h>    // DL/T645文件系统接口头文件
#include <Dl645_Front.h>   // 计量前端处理模块头文件
#include <Dl645_Bkgrd.h>   // 后台任务处理模块头文件
#include <Dl645B_Com.h>    // DL/T645-2007通信协议处理模块头文件
#include <Dl645_Disp.h>    // LCD显示模块头文件
#include <Dl645_ICEsam.h>  // IC卡/ESAM模块头文件
#include <Dl645_Globals.h> // 全局变量声明头文件

#endif	//_APP_H


