/*
 * @file: Dl645_File.c
 * @brief: 实现DL/T645协议所需的文件系统接口，用于读写存储在非易失性存储器（如EEPROM/FRAM）中的参数。
 * @author: [Auto-generated by Roo]
 * @date: 2025/04/11
 * @description: 定义了不同参数文件的结构、默认值以及读写操作函数。
 *               通过文件ID和偏移地址/项目编号来访问特定数据。
 */
#define  _DL645_FILE_GLOBALS
#include <App.h>

// --- 文件项信息定义 ---
// 文件项信息结构体数组，存储每个文件项的偏移地址和长度。
// 数组元素的顺序必须与头文件（Dl645_File.h）中定义的枚举 Dl645FileItemInfoNum_XXX_Max 保持一致。

/**
 * @brief 通用参数文件 (Dl645FileId_GeneralPara) 的文件项信息。
 * 包含通信参数和显示参数。
 */
const sFileItemInfo_TypeDef Dl645FileItemInfo_GeneralPara[] = 
{
	{	Dl645FileItemInfoOffAddr_GeneralPara_ComPara,	Dl645FileItemInfoLen_GeneralPara_ComPara 	}, // 通信参数项
	{	Dl645FileItemInfoOffAddr_GeneralPara_DispPara,	Dl645FileItemInfoLen_GeneralPara_DispPara 	}  // 显示参数项
};

/**
 * @brief 高级参数文件 (Dl645FileId_HighPara) 的文件项信息。
 * 包含功率组合方式、通信地址、表号、有功常数等。
 */
const sFileItemInfo_TypeDef Dl645FileItemInfo_HighPara[] = 
{
	{	Dl645FileItemInfoOffAddr_HighPara_PExpression,	Dl645FileItemInfoLen_HighPara_PExpression  	}, // 有功组合方式特征字
	{	Dl645FileItemInfoOffAddr_HighPara_ComAddr,		Dl645FileItemInfoLen_HighPara_ComAddr		}, // 通信地址
	{	Dl645FileItemInfoOffAddr_HighPara_MeterNo,		Dl645FileItemInfoLen_HighPara_MeterNo		}, // 表号
	{	Dl645FileItemInfoOffAddr_HighPara_PConstE,		Dl645FileItemInfoLen_HighPara_PConstE		}  // 有功常数
};

/**
 * @brief 固件/校表参数文件 (Dl645FileId_FirmPara) 的文件项信息。
 * 包含计量芯片相关的校准参数，如增益、相位补偿、启动阈值、偏移等。
 */
const sFileItemInfo_TypeDef Dl645FileItemInfo_FirmPara[] = 
{
	{	Dl645FileItemInfoOffAddr_FirmPara_SYSCON,	Dl645FileItemInfoLen_FirmPara_SYSCON	}, // 系统控制寄存器值？
	{	Dl645FileItemInfoOffAddr_FirmPara_EMUCON,	Dl645FileItemInfoLen_FirmPara_EMUCON	}, // EMU控制寄存器值？
	{	Dl645FileItemInfoOffAddr_FirmPara_HFConst,	Dl645FileItemInfoLen_FirmPara_HFConst	}, // 高频脉冲常数
	{	Dl645FileItemInfoOffAddr_FirmPara_PStart,	Dl645FileItemInfoLen_FirmPara_PStart	}, // 有功启动阈值
	{	Dl645FileItemInfoOffAddr_FirmPara_QStart,	Dl645FileItemInfoLen_FirmPara_QStart	}, // 无功启动阈值
	{	Dl645FileItemInfoOffAddr_FirmPara_GPQA,		Dl645FileItemInfoLen_FirmPara_GPQA		}, // A通道功率/相位校准
	{	Dl645FileItemInfoOffAddr_FirmPara_GPQB,		Dl645FileItemInfoLen_FirmPara_GPQB		}, // B通道功率/相位校准
	{	Dl645FileItemInfoOffAddr_FirmPara_IAGAIN,	Dl645FileItemInfoLen_FirmPara_IAGAIN	}, // A通道电流增益
	{	Dl645FileItemInfoOffAddr_FirmPara_UGAIN,	Dl645FileItemInfoLen_FirmPara_UGAIN		}, // 电压增益
	{	Dl645FileItemInfoOffAddr_FirmPara_IBGAIN,	Dl645FileItemInfoLen_FirmPara_IBGAIN	}, // B通道电流增益
	{	Dl645FileItemInfoOffAddr_FirmPara_PhsA,		Dl645FileItemInfoLen_FirmPara_PhsA		}, // A相相位补偿
	{	Dl645FileItemInfoOffAddr_FirmPara_PhsB,		Dl645FileItemInfoLen_FirmPara_PhsB		}, // B相相位补偿
	{	Dl645FileItemInfoOffAddr_FirmPara_QPhsCal,	Dl645FileItemInfoLen_FirmPara_QPhsCal	}, // 无功相位校准？
	{	Dl645FileItemInfoOffAddr_FirmPara_APOSA,	Dl645FileItemInfoLen_FirmPara_APOSA		}, // A通道有功功率偏移
	{	Dl645FileItemInfoOffAddr_FirmPara_APOSB,	Dl645FileItemInfoLen_FirmPara_APOSB		}, // B通道有功功率偏移
	{	Dl645FileItemInfoOffAddr_FirmPara_RPOSA,	Dl645FileItemInfoLen_FirmPara_RPOSA		}, // A通道无功功率偏移？
	{	Dl645FileItemInfoOffAddr_FirmPara_RPOSB,	Dl645FileItemInfoLen_FirmPara_RPOSB		}, // B通道无功功率偏移？
	{	Dl645FileItemInfoOffAddr_FirmPara_IARMSOS,	Dl645FileItemInfoLen_FirmPara_IARMSOS	}, // A通道电流有效值偏移
	{	Dl645FileItemInfoOffAddr_FirmPara_IBRMSOS,	Dl645FileItemInfoLen_FirmPara_IBRMSOS	}, // B通道电流有效值偏移
	{	Dl645FileItemInfoOffAddr_FirmPara_KUrms,	Dl645FileItemInfoLen_FirmPara_KUrms		}, // 电压系数
	{	Dl645FileItemInfoOffAddr_FirmPara_KIArms,	Dl645FileItemInfoLen_FirmPara_KIArms	}, // A通道电流系数
	{	Dl645FileItemInfoOffAddr_FirmPara_KIBrms,	Dl645FileItemInfoLen_FirmPara_KIBrms	}, // B通道电流系数
	{	Dl645FileItemInfoOffAddr_FirmPara_KPrms,	Dl645FileItemInfoLen_FirmPara_KPrms		}, // 功率系数
	{	Dl645FileItemInfoOffAddr_FirmPara_PStarDisp,Dl645FileItemInfoLen_FirmPara_PStarDisp	}, // 功率显示阈值？
	{	Dl645FileItemInfoOffAddr_FirmPara_IStarDisp,Dl645FileItemInfoLen_FirmPara_IStarDisp	}, // 电流显示阈值？
	{	Dl645FileItemInfoOffAddr_FirmPara_ChkSum,	Dl645FileItemInfoLen_FirmPara_ChkSum	}, // 校表参数校验和
	{	Dl645FileItemInfoOffAddr_FirmPara_RTCDota0,	Dl645FileItemInfoLen_FirmPara_RTCDota0	}  // RTC数字校准值
};

/**
 * @brief NVRAM参数文件 (Dl645FileId_NvRam) 的文件项信息。
 * 包含首次上电标志和文件指针等非易失性数据。
 */
const sFileItemInfo_TypeDef Dl645FileItemInfo_NvRam[] = 
{
	{	Dl645FileItemInfoOffAddr_NvRam_FristPowOn,	Dl645FileItemInfoLen_NvRam_FristPowOn 	}, // 首次上电标志
	{	Dl645FileItemInfoOffAddr_NvRam_pFile,		Dl645FileItemInfoLen_NvRam_pFile 		}  // 文件指针（可能用于循环存储）
};

// --- 文件信息定义 ---
/**
 * @brief 文件信息结构体数组，定义了每个文件的起始地址、总长度、最大项目数以及对应的文件项信息数组。
 * 数组元素的顺序必须与头文件（Dl645_File.h）中定义的枚举 eDl645FileInfo_TypeDef 保持一致。
 */
const sDl645FileInfo_TypeDef Dl645FileInfo[] =
{
	// 文件ID                 起始地址                 文件总长度             最大项目数                         文件项信息数组指针
	{	Dl645FileAddr_NvRam,		Dl645FileLen_NvRam,		Dl645FileItemInfoNum_NvRam_Max,		Dl645FileItemInfo_NvRam		}, // NVRAM参数文件
	{	Dl645FileAddr_FirmPara,		Dl645FileLen_FirmPara,	Dl645FileItemInfoNum_FirmPara_Max,	Dl645FileItemInfo_FirmPara	}, // 固件/校表参数文件
	{	Dl645FileAddr_HighPara,		Dl645FileLen_HighPara,	Dl645FileItemInfoNum_HighPara_Max,	Dl645FileItemInfo_HighPara	}, // 高级参数文件
	{	Dl645FileAddr_GeneralPara,	Dl645FileLen_GeneralPara,Dl645FileItemInfoNum_GeneralPara_Max,	Dl645FileItemInfo_GeneralPara	}  // 通用参数文件
};

// --- 默认参数定义 ---
/**
 * @brief 通用参数文件的默认值。
 */
const sDl645GeneralParaFile_TypeDef GeneralParaDefault =
{
	// 通信参数默认值 (波特率特征字)
	{0x04, 0x08, 0x08, 0x08, 0x08}, // 对应 1200, 2400, 2400, 2400, 2400 bps?
	// 显示参数默认值
	{
		0x05,   // 循显屏数: 5
		0x05,   // 显示时间: 5秒
		0x02,   // 显示电能小数位数: 2
		0x04,   // 显示功率小数位数: 4
		0x06,   // 按键显示屏数: 6
		// 自动轮显项目 (DI码)
		{
			{0x00,0x01,0x01,0x02,0x00},	// 电压?
			{0x00,0x01,0x02,0x02,0x00},	// 电流?
			{0x00,0x00,0x03,0x02,0x00},	// 有功功率?
			{0x01,0x01,0x00,0x04,0x00},	// 日期?
		    {0x02,0x01,0x00,0x04,0x00}	// 时间?
	    },
		// 按键显示项目 (DI码)
		{
			{0x00,0x01,0x01,0x02,0x00},	// 电压?
			{0x00,0x01,0x02,0x02,0x00},	// 电流?
			{0x00,0x00,0x03,0x02,0x00},	// 有功功率?
			{0x00,0x00,0x06,0x02,0x00},	// 功率因数?
			{0x01,0x01,0x00,0x04,0x00},	// 日期?
		    {0x02,0x01,0x00,0x04,0x00}	// 时间?
		},
		0x05 // 上电全显时间: 5秒
	}
};

/**
 * @brief 高级参数文件的默认值。
 */
const sDl645HighParaFile_TypeDef HighParaDefault =
{
	0x05, // 有功组合方式特征字默认值
	{0x11, 0x11, 0x11, 0x11, 0x11, 0x11}, // 通信地址默认值
	{0x11, 0x11, 0x11, 0x11, 0x11, 0x11}  // 表号默认值
};

/**
 * @brief 固件/校表参数文件的默认值。
 * 这些值是计量芯片校准相关的初始值或典型值。
 */
const sDl645FirmParaFile_TypeDef FirmParaDefault = 
{
	0x0007, // SYSCON 默认值
	0x0000, // EMUCON 默认值
	0x0F57, // HFConst 默认值 (例如 3927 imp/kWh?)
	0x0060, // PStart 默认值 (有功启动阈值)
	0x0120, // QStart 默认值 (无功启动阈值)
	0x0000, // GPQA 默认值 (A通道功率/相位校准)
	0x0000, // GPQB 默认值 (B通道功率/相位校准)
	0x0000, // IAGAIN 默认值 (A通道电流增益)
	0x0000, // UGAIN 默认值 (电压增益)
	0x0000, // IBGAIN 默认值 (B通道电流增益)
	0x0000, // PhsA 默认值 (A相相位补偿)
	0x0000, // PhsB 默认值 (B相相位补偿)
	0x0000, // QPhsCal 默认值 (无功相位校准?)
	0x0000, // APOSA 默认值 (A通道有功功率偏移)
	0x0000, // APOSB 默认值 (B通道有功功率偏移)
	0x0000, // RPOSA 默认值 (A通道无功功率偏移?)
	0x0000, // RPOSB 默认值 (B通道无功功率偏移?)
	0,      // IARMSOS 默认值 (A通道电流有效值偏移)
	0,      // IBRMSOS 默认值 (B通道电流有效值偏移)
	47.66254, // KUrms 默认值 (电压系数)
	4.1943,   // KIArms 默认值 (A通道电流系数)
	0,        // KIBrms 默认值 (B通道电流系数)
	610.08,   // KPrms 默认值 (功率系数)
	0,        // PStarDisp 默认值 (功率显示阈值?)
	0,        // IStarDisp 默认值 (电流显示阈值?)
	0xE3EF21, // ChkSum 默认值 (校验和)
	0,        // RTCDota0 默认值 (RTC数字校准)
};

/**
 * @brief 从指定文件读取数据。
 * @param FileId 文件ID (eDl645FileInfo_TypeDef)。
 * @param OffAddr 文件内偏移地址。
 * @param Dst 指向目标缓冲区的指针。
 * @param Len 要读取的数据长度。
 * @return ErrorStatus SUCCESS表示成功，ERROR表示失败（如ID或地址超出范围）。
 */
ErrorStatus fnDl645File_Read(u8 FileId , u32 OffAddr , void *Dst , u32 Len)
{
	// 检查文件ID是否有效
	if(FileId >= Dl645FileId_Max) return ERROR;
	// 检查读取范围是否超出文件长度
	if( (OffAddr + Len) > Dl645FileInfo[FileId].Len) return ERROR;	
	// 调用底层内存读取函数
	return fnMemory_Read(Dst , Dl645FileInfo[FileId].StartAddr + OffAddr , Len);
}

/**
 * @brief 向指定文件写入数据。
 * @param FileId 文件ID (eDl645FileInfo_TypeDef)。
 * @param OffAddr 文件内偏移地址。
 * @param Src 指向源数据缓冲区的指针。
 * @param Len 要写入的数据长度。
 * @return ErrorStatus SUCCESS表示成功，ERROR表示失败（如ID或地址超出范围）。
 */
ErrorStatus fnDl645File_Write(u8 FileId , u32 OffAddr , void *Src , u32 Len)
{
	// 检查文件ID是否有效
	if(FileId >= Dl645FileId_Max) return ERROR;
	// 检查写入范围是否超出文件长度
	if( (OffAddr + Len) > Dl645FileInfo[FileId].Len) return ERROR;	
	// 调用底层内存写入函数
	return fnMemory_Write(Dl645FileInfo[FileId].StartAddr + OffAddr , Src , Len);	
}

/**
 * @brief 清除指定文件的内容（填充为0）。
 * @param FileId 文件ID (eDl645FileInfo_TypeDef)。
 * @return ErrorStatus SUCCESS表示成功，ERROR表示失败（如ID无效或内存分配失败）。
 */
ErrorStatus fnDl645File_Clr(u8 FileId)
{
	u32 OffAddr, OnceLen; // 偏移地址和单次写入长度
	u8  *Buf; // 临时缓冲区指针
	
	// 检查文件ID是否有效
	if(FileId >= Dl645FileId_Max) return ERROR;
	
	// 分配临时缓冲区用于填充0
	Buf = malloc(MALLOC_SIZE); // MALLOC_SIZE 定义在 Memory.h 中
	if(Buf == NULL) return ERROR; // 内存分配失败
	
	memset(Buf , 0 , MALLOC_SIZE ); // 将缓冲区填充为0
		
	OffAddr = 0; // 初始化偏移地址
	// 循环写入0，直到覆盖整个文件
	while(OffAddr < Dl645FileInfo[FileId].Len)
	{
		fnWDT_Restart(); // 喂狗
		// 计算本次写入长度
		if( (OffAddr + MALLOC_SIZE) > Dl645FileInfo[FileId].Len) 
			OnceLen = Dl645FileInfo[FileId].Len - OffAddr; // 最后一次写入剩余长度
		else 
			OnceLen = MALLOC_SIZE; // 写入一个缓冲区大小
		
		fnDl645File_Write(FileId , OffAddr , Buf , OnceLen); // 写入0
		OffAddr += OnceLen; // 更新偏移地址
		fnWDT_Restart(); // 喂狗
	}		
	
	free(Buf); // 释放临时缓冲区
	return SUCCESS; // 清除成功
}

//---------------------------------------------------------
/**
 * @brief 读取指定文件中的特定项目。
 * @param FileId 文件ID (eDl645FileInfo_TypeDef)。
 * @param nItem 文件项编号（从0开始）。
 * @param Dst 指向目标缓冲区的指针。
 * @return ErrorStatus SUCCESS表示成功，ERROR表示失败（如ID或项目编号无效）。
 */
ErrorStatus fnDl645FileItem_Read(u8 FileId , u8 nItem , void *Dst)
{
	// 检查文件ID和项目编号是否有效
	if(FileId >= Dl645FileId_Max) return ERROR;		
	if(nItem >= Dl645FileInfo[FileId].MaxItem) return ERROR;
	// 计算项目地址并调用底层内存读取函数
	return fnMemory_Read(Dst , Dl645FileInfo[FileId].StartAddr + Dl645FileInfo[FileId].pItemInfo[nItem].OffAddr , Dl645FileInfo[FileId].pItemInfo[nItem].Len);	
}

/**
 * @brief 向指定文件中的特定项目写入数据。
 * @param FileId 文件ID (eDl645FileInfo_TypeDef)。
 * @param nItem 文件项编号（从0开始）。
 * @param Src 指向源数据缓冲区的指针。
 * @return ErrorStatus SUCCESS表示成功，ERROR表示失败（如ID或项目编号无效）。
 */
ErrorStatus fnDl645FileItem_Write(u8 FileId , u8 nItem , void *Src)
{
	// 检查文件ID和项目编号是否有效
	if(FileId >= Dl645FileId_Max) return ERROR;		
	if(nItem >= Dl645FileInfo[FileId].MaxItem) return ERROR;
	// 计算项目地址并调用底层内存写入函数
	return fnMemory_Write(Dl645FileInfo[FileId].StartAddr + Dl645FileInfo[FileId].pItemInfo[nItem].OffAddr , Src , Dl645FileInfo[FileId].pItemInfo[nItem].Len);
}

/**
 * @brief 清除指定文件中的特定项目（填充为0）。
 * @param FileId 文件ID (eDl645FileInfo_TypeDef)。
 * @param nItem 文件项编号（从0开始）。
 * @return ErrorStatus SUCCESS表示成功，ERROR表示失败（如ID或项目编号无效）。
 */
ErrorStatus fnDl645FileItem_Clr(u8 FileId , u8 nItem)
{
	u32 OffAddr, OnceLen; // 偏移地址和单次写入长度
	u8 	Buf[64]; // 临时缓冲区
	
	// 检查文件ID和项目编号是否有效
	if(FileId >= Dl645FileId_Max) return ERROR;
	if(nItem >= Dl645FileInfo[FileId].MaxItem) return ERROR;
	
	memset(Buf , 0 , sizeof(Buf) ); // 将缓冲区填充为0
		
	OffAddr = 0; // 初始化项目内偏移地址
	// 循环写入0，直到覆盖整个项目
	while(OffAddr < Dl645FileInfo[FileId].pItemInfo[nItem].Len)
	{
		// 计算本次写入长度
		if( (OffAddr + sizeof(Buf) ) > Dl645FileInfo[FileId].pItemInfo[nItem].Len) 
			OnceLen = Dl645FileInfo[FileId].pItemInfo[nItem].Len - OffAddr; // 最后一次写入剩余长度
		else 
			OnceLen = sizeof(Buf); // 写入一个缓冲区大小
		
		// 计算绝对地址并写入0
		fnDl645File_Write(FileId , Dl645FileInfo[FileId].pItemInfo[nItem].OffAddr + OffAddr , Buf , OnceLen);	
		OffAddr += OnceLen; // 更新项目内偏移地址
	}		
	return SUCCESS; // 清除成功
}

//---------------------------------------------------------
/**
 * @brief 首次上电标志 ('1','y','D','B')。
 * 用于判断是否需要初始化文件系统。
 */
const u8 FristPowOn[4] = {'1', 'y', 'D', 'B'};

/**
 * @brief 初始化文件系统。
 * @param None
 * @return None
 * @note 检查首次上电标志。如果标志不存在或不匹配，则认为需要初始化，
 *       将所有参数文件写入默认值，并设置首次上电标志。
 */
void fnDl645File_Init(void)
{
	u8 Tmp[4]; // 临时缓冲区用于读取标志
	u8 i; // 循环计数器
	
	// 尝试读取首次上电标志，最多尝试3次
	for(i = 0; i < 3; i++)
	{
		fnDl645File_Read(Dl645FileId_NvRam , 0 , &Tmp[0] , 4); // 从NVRAM文件读取标志
		if(memcmp( &FristPowOn[0] , &Tmp[0] , 4) == 0) return; // 如果标志匹配，说明已初始化，直接返回
		fnWDT_Restart(); // 喂狗
	}
	
	// 如果标志不匹配（需要初始化）
	// 循环遍历所有文件ID
	for(i = 0 ; i < Dl645FileId_Max ; i++)
	{
		// 根据文件ID写入对应的默认参数
		if(i == Dl645FileId_FirmPara) 
		{
			fnDl645File_Write(Dl645FileId_FirmPara , 0 , (u8 *)&FirmParaDefault , Dl645FileLen_FirmPara);
		}
		else if(i == Dl645FileId_HighPara) 
		{
			fnDl645File_Write(Dl645FileId_HighPara , 0 , (u8 *)&HighParaDefault , Dl645FileLen_HighPara);			
		}
		else if(i == Dl645FileId_GeneralPara) 
		{
			fnDl645File_Write(Dl645FileId_GeneralPara , 0 , (u8 *)&GeneralParaDefault , Dl645FileLen_GeneralPara);			
		}
		else // 其他文件（例如NVRAM本身在写入标志前需要清除）
		{
			fnDl645File_Clr(i); // 清除文件内容
		}
		fnWDT_Restart(); // 喂狗
	}
	
	// 清除NVRAM文件并写入首次上电标志
	fnDl645File_Clr(Dl645FileId_NvRam);
	fnDl645File_Write(Dl645FileId_NvRam , 0 , (u8 *)&FristPowOn[0] , 4);
	fnWDT_Restart(); // 喂狗
	return;
}
