/*
 * @file: Dl645_Disp.h
 * @brief: LCD显示模块的头文件。
 * @author: [Auto-generated by Roo]
 * @date: 2025/04/11
 * @description: 定义了LCD显示相关的常量、数据结构和函数声明。
 */
#ifndef __DL645_DISP_H
#define __DL645_DISP_H

// 条件编译宏，用于定义全局变量或外部引用
#ifdef   DL645_DISP_GLOBALS
	#define  DL645DISP_EXT 	// 如果定义了DL645_DISP_GLOBALS，则定义为空
#else
	#define  DL645DISP_EXT  extern // 否则定义为extern
#endif

/**
 * @brief 显示会话数据结构体。
 * 用于管理人机交互过程中的显示状态和参数。
 */
typedef struct {
	u8  Mode;           // 当前显示模式: 0=自动轮显, 1=按键显示, 2=遥控显示 (参考 DISPLAYAUTO, DISPLAYKEY, DISPLARYEMOTE)
	u8  AutoSerialNo;   // 自动轮显模式下的当前项目序号 (0-99)
	u8  KeySeriaNo;     // 按键显示模式下的当前项目序号 (0-99)
	u8  Stamp;          // 通用时间戳，用于轮显间隔或按键超时计时
	u8	CardDispStamp;  // 卡操作相关显示的时间戳？
	u8  EventErr1;      // 事件/错误标志1？
	u8  EventErr2;      // 事件/错误标志2？
	u8  EventKeyErr;    // 按键相关错误标志？
	u8	BkLightFlag;	// 背光点亮标志 (例如 0x5A 表示点亮)
	u8  BkLightStamp;   // 背光超时计时器
	u8  RemoteStamp;    // 遥控操作超时计时器？
  	u8  Item[5];        // 当前显示的项目的标识符 (通常包含DI码等信息)
  	u8  lItem[5];       // 上一个显示的项目？ (注释 "1项目" 不清晰)
	u8  LcdCount;		// LCD计数器？ (用途不明确)
	u8  DigitPosition;  // 数字操作位置？ (可能用于参数设置)
	u8 	DisplyErrFlag;  // 显示刷新标志 (1表示需要刷新)
	u8	AllOnDispTime;	// 上电全显剩余时间
} sDl645B_Session_TYPE;

// 显示模式定义
#define DISPLAYAUTO     0 // 自动轮显模式
#define DISPLAYKEY      1 // 按键显示模式
#define DISPLARYEMOTE   2 // 遥控显示模式 (注释为 "遥控器代码")
#define InvalidItem     0xff // 无效显示项目标识

// 函数声明
/**
 * @brief 初始化LCD显示模块。
 */
extern void fnDl645Disp_Init(void);

/**
 * @brief LCD显示会话执行函数，处理模式切换、项目切换、超时等。
 */
extern void fnDl645Disp_SessionExec(void);

/**
 * @brief 根据数据类型格式化数据并在LCD上显示。
 * @param Buf 指向数据的指针。
 * @param DataType 数据类型代码。
 * @param Length 数据长度。
 */
extern void fnDl645Disp_Data(u8 *Buf, u8 DataType, u8 Length);

/**
 * @brief 刷新LCD上的状态指示符（如通信、功率方向）。
 */
extern void fnDl645Disp_RefreshStatus(void);

/**
 * @brief 根据当前显示项目刷新LCD数据区。
 */
extern void fnDl645Disp_RefreshDispData(void);

/**
 * @brief 显示瞬时变量数据。
 */
extern void fnDl645Disp_Variable(void);

/**
 * @brief 显示通用参数数据（如日期、时间）。
 */
extern void fnDl645Disp_GeneralPara(void);

/**
 * @brief 显示其他信息（函数未在.c中实现）。
 * @param Buf 指向消息数据的指针。
 */
extern void fnDl645Disp_OtherMessage(const u16 *Buf);

/**
 * @brief 显示费率和月份/次数？（函数未在.c中实现）。
 * @param Type 类型。
 * @param Data 数据。
 */
extern void fnDl645Disp_RateMonthTimes(u8 Type, u8 Data);

#endif // __DL645_DISP_H
