/*
 * @file: Dl645_Globals.c
 * @brief: 定义项目中使用的全局变量。
 * @author: [Auto-generated by Roo]
 * @date: 2025/04/11
 * @description: 此文件通过定义 _DL645_GLOBALS 宏，
 *               使得在 Dl645_Globals.h 中声明的全局变量在此处被实例化。
 *               实际的变量声明请参见 Dl645_Globals.h。
 */

#define  _DL645_GLOBALS // 定义此宏以实例化全局变量
#include <includes.h> // 包含项目的主要头文件

//============================
//	定义DL645协议全局变量
//============================
// 此文件本身不包含变量的显式定义代码，
// 全局变量的定义依赖于在 Dl645_Globals.h 中使用 DL645_EXT 宏的声明方式。
// 当 _DL645_GLOBALS 被定义时，DL645_EXT 宏为空，变量被定义；
// 在其他包含 Dl645_Globals.h 的文件中，DL645_EXT 宏为 extern，变量被声明为外部引用。
