/*
 * @file: Dl645_Globals.h
 * @brief: 声明项目中使用的全局变量。
 * @author: [Auto-generated by Roo]
 * @date: 2025/04/11
 * @description: 使用 DL645_EXT 宏来控制变量是在此文件定义还是在其他文件声明为外部引用。
 *               实际定义发生在 Dl645_Globals.c 文件中（通过定义 _DL645_GLOBALS 宏）。
 */
#ifndef  _DL645_GLOBALS_H
#define  _DL645_GLOBALS_H

// 条件编译宏，用于全局变量的定义或声明
#ifdef   _DL645_GLOBALS
	#define  DL645_EXT // 如果在 Dl645_Globals.c 中，定义为空，表示定义变量
#else
	#define  DL645_EXT  extern // 在其他文件中，定义为 extern，表示声明外部变量
#endif

//---------------- 全局变量声明 --------------------
DL645_EXT 	u16		SysStamp;	    // 系统主计时器/节拍计数器，单位通常为毫秒 (1ms)
DL645_EXT	sDF01	SysClock;       // 系统当前时间结构体 (包含年、月、日、时、分、秒、星期)
DL645_EXT 	u16		SysStamp500;    // 500ms 计时器/节拍计数器
DL645_EXT 	u16		GataSysStamp;	// 门控/继电器相关的系统时间戳？ (Gata可能指Gate)

// --- 各模块全局数据结构 ---
// DL645_EXT 	u8 	LCDDMABuf[250] __attribute__(( at(0x10000100) )); // LCD DMA缓冲区 (被注释掉，可能未使用或改用其他方式)
DL645_EXT	sDl645FrontTmp_TypeDef	Dl645FrontTmp; // 计量前端临时数据结构体
DL645_EXT	sDl645Front_TypeDef		Dl645Front;    // 计量前端主数据结构体
DL645_EXT 	sDl645Bkgrd_TypeDef 	Dl645Bkgrd;    // 后台任务数据结构体
DL645_EXT 	sComPack_TypeDef 		ComPack[SCOM_PORT_MAX]; // 通信端口数据包结构体数组 (每个端口一个)
DL645_EXT	sDl645B_Session_TYPE 	Dl645Session;  // 显示会话管理结构体
DL645_EXT	sDl645FirmParaFile_TypeDef	Dl645FirmPara; // 固件/校表参数结构体 (从文件加载到RAM)
DL645_EXT	sD645Inactive_TypeDef	Dl645Inactive; // 低功耗/非活动状态管理结构体

// --- 全局缓冲区 ---
DL645_EXT	u8	BufTemp[270]; // 通用临时缓冲区 (大小270字节)
DL645_EXT	u8	DispBuf[240]; // 显示缓冲区？ (大小240字节)

// --- 其他全局标志或变量 ---
DL645_EXT	u32	CMPFlag;      // 比较器(Comparator)相关标志？
DL645_EXT 	sICEsamPack_TypeDef		ICEsamComm;    // IC卡/ESAM通信数据包结构体
DL645_EXT	u32	FlashAdMax;   // Flash最大地址？ (可能用于存储管理)

// --- 系统相关外部变量 ---
/**
 * @brief 初始堆栈指针。
 * 由启动文件 (startup_RN8213.s) 定义，链接器使用。
 */
extern		int32_t __initial_sp;

//--------------------------------------------

#endif	//_DL645_GLOBALS_H



















