/*
 * @file: includes.h
 * @brief: 项目顶层包含文件。
 * @author: [Auto-generated by Roo]
 * @date: 2025/04/11
 * @description: 此文件用于包含驱动层和应用层的主要头文件，并定义全局宏。
 */
#ifndef  _INCLUDES_H
#define  _INCLUDES_H

// 包含驱动层库的主头文件，该文件应包含所有底层驱动接口的声明
#include <Drive_Lib.h>
// 包含应用层的主头文件，该文件包含所有应用模块的头文件和配置宏
#include <App.h>


//---------------- 全局宏定义 --------------------
/**
 * @brief 软件调试模式宏定义。
 * 当定义为 1 时，启用软件调试相关的功能（例如，可能跳过某些硬件等待或增加模拟数据）。
 * 当定义为 0 或未定义时，禁用调试功能，用于发布版本。
 */
#define 	SOFT_DEBUG				1

#endif	// _INCLUDES_H








