/*
 * @file: Memory.h
 * @brief: 存储器操作接口头文件。
 * @author: [Auto-generated by Roo]
 * @date: 2025/04/11
 * @description: 定义了存储器相关的宏和读写函数的声明。
 */
#ifndef _DL645_MEMORY_H
#define _DL645_MEMORY_H


// --- 宏定义 ---

/**
 * @brief 定义动态内存分配的默认大小。
 * 可能用于 fnDl645File_Clr 等函数中的临时缓冲区。
 */
#define MALLOC_SIZE					100

/**
 * @brief 定义外部非易失性存储器 (EEPROM/FRAM AT24C256) 的起始地址。
 * 这个地址是MCU访问外部存储器的内存映射地址或基地址。
 * 0x92000000: 这个地址值需要根据具体的硬件平台和内存映射来确定其含义。
 */
#define AT24C256_START_ADDR 		0x92000000 // 32K字节存储器的起始地址

/**
 * @brief 定义外部非易失性存储器 (EEPROM/FRAM AT24C256) 的大小。
 * 0x8000 表示 32 * 1024 = 32768 字节，即 32KB。
 */
#define AT24C256_SIZE				0x00008000

// --- 函数声明 ---

/**
 * @brief 从非易失性存储器读取数据。
 * @param Dst 指向存储读取数据的目标缓冲区。
 * @param Src 要读取的存储器绝对地址。
 * @param DatLen 要读取的数据长度（字节）。
 * @return ErrorStatus SUCCESS表示读取成功，ERROR表示失败。
 */
extern ErrorStatus fnMemory_Read(u8 *Dst , u32 Src , u32 DatLen);

/**
 * @brief 向非易失性存储器写入数据。
 * @param Dst 要写入的存储器绝对地址。
 * @param Src 指向包含待写入数据的源缓冲区。
 * @param DatLen 要写入的数据长度（字节）。
 * @return ErrorStatus SUCCESS表示写入成功，ERROR表示失败。
 */
extern ErrorStatus fnMemory_Write(u32 Dst , u8 *Src , u32 DatLen);


#endif // _DL645_MEMORY_H











